### ISSUE TITLE
Save receivedEmail content to DB2 tables.

### ISSUE THREAD

**Issue by johntechie9898** [redamessoudi/subethasmtp-springboot#1]
Hello, 

How do i save the receivedEmail content to DB2 tables. I want to save:  from, to, subject, emailbody and attachments.
what is the approach ?? 

could you please share some inputs.

**Comment by redamessoudi** [comment]
Hello @rachakonda ,
You can store the receivedEmail on any database management system (e.g DB2, MySQL or MongoDB, ...) by creating a table named per example `received_emails` and create some columns in it like `ID`, `from`, `to`, `subject` and `content`.
To store `receivedEmail` model, you can create a new service (e.g `EmailService`) which will take care of the storage on your DB2.
I hope it's clear for you. Don't hesitate if you have another question.

**Comment by johntechie9898** [comment]
Thanks for your reply 
Any sample code ?? For db2
I believe data source bean has to be created and mapper class has to be initiated right ??

**Comment by redamessoudi** [comment]
You can use this example [spring boot and db2](https://github.com/springframeworkguru/spring-boot-db2-example) and/or [watch the video](https://www.youtube.com/watch?v=6IQPwmPh3TU).
In the links above, the `Product` class/entity can be comparable to `ReceivedEmail`.

**Comment by johntechie9898** [comment]
@redamessoudi  i have looked at the above mentioned example that is jpa based.. 
I wanted spring boot app + mybatis + db2. 


I'm looking for a example for :
spring boot app (standalone but not webapp) + mybatis + db2 using annotation based.(insert and update)
I have tried using the example which you have mentioned but no luck.

How to get a data source(this is little tricky I think) in standalone app ? for inserts or updates ?

spring boot app + mybatis + db2 using annotation based.

**Comment by redamessoudi** [comment]
Hi @johntechie9898 
you can use any stuff you already did with Spring Boot, mybatis and db2 or that you can find on internet. 
Having SubethaSMTP as dependency will not affect your project.
The aim of this repository was to present how to handle incoming emails, adding a data source support is another topic which is not covered.

**Comment by johntechie9898** [comment]
@redamessoudi i have a working project now. thank you.

**Comment by redamessoudi** [comment]
You're welcome. I'll close the issue.
